### PR TITLE
Use of ESLINT for a more consistent code

### PR DESCRIPTION
**Pull request by busybox11**
Settings used :
 - Double quotes
 - Semicolons
 - Tabs instead of spaces

### CODE REVIEW

**Comment by AryToNeX** [comment]
oh man this would need a rebase

**Comment by MasicoreLord** [comment]
Use Typescript for source code, kidding, use what you want.

**Comment by busybox11** [comment]
I can close my PR if you want

**Comment by busybox11** [comment]
Oops, clicked on the wrong button. I think this would end up like this anyway

**Comment by AryToNeX** [comment]
Not exactly; you'll just need to rebase it

**Pull request closed without merging**
