### PR TITLE
Make window resizeable from title bar

### PR DESCRIPTION
**Pull request by the-garlic-os**
Right now, when it comes to title bar behavior, a theme designer has two options: either A) let the window be resizeable from the title bar at the cost of a thin, opaque stripe at the top of the window (which doesn't look very good), or B) style the title bar in such a way that the stripe isn't there at the cost of no longer being able to resize Discord from the top of the window. The second option is how this example theme does it, which I suspect many people who wish to design a theme for Glasscord will base theirs off of.

This change brings the best of both worlds! The code that hides the opaque stripe (and breaks resizing from the title bar) has been replaced with code that will seamlessly cover up the opaque bar while _still_ letting users resize the window from the top edge.

### CODE REVIEW

**Comment by AryToNeX** [comment]
@dudeamax99 can you test this pls?

**Comment by PoorPocketsMcNewHold** [comment]
I suppose it has been merged already? 58feb40

**Comment by AryToNeX** [comment]
nope lol I just updated their PR following some changes in my master branch

**Comment by the-garlic-os** [comment]
Is this bugfix going to be merged soon?

**Comment by AryToNeX** [comment]
Sorry I haven't been active for a while (due to... stuff). I have yet to test those changes personally. If I can have someone of the Glasscord Contributors Team test and approve, then it will be merged. I just don't have the time to do it myself.

**Comment by busybox11** [comment]
I wish I could, but this will not have any effect with i3wm. I'm going to install xfce if I have the time, but I think I will not be able to test it, sadly.

**Comment by AryToNeX** [comment]
I tested this personally; I cannot resize the window from the top bar when using the OS X style on Linux.

**Comment by AryToNeX** [comment]
@the-garlic-os you still here??

**Comment by the-garlic-os** [comment]
I see. I just tried top resizing with the OS X style on Windows and I can confirm that it does not work. I will keep looking for a solution that works on every window style.

**Comment by the-garlic-os** [comment]
See if this will work. I added a couple new rules that should make Discord resizable from the top edge on the OS X theme. It moves the main header (the one with the channel name and search bar) off of the top edge while still looking the same. For some reason, the header's being right up against the top edge of the window was keeping Discord from being top resized over the area that it covered.

**Comment by AryToNeX** [comment]
looks fine to me now

**Comment by the-garlic-os** [comment]
Awesome. Thank you!

**Pull request merged**
